apply plugin: 'groovy'
apply plugin: 'maven'

group = 'info.gianlucacosta.aurora'
archivesBaseName = 'aurora'
version = '0.0.0-SNAPSHOT'


description = 'Elegant Gradle projects for the JVM'


repositories {
    mavenLocal()

    mavenCentral()
}

dependencies {
    compile localGroovy()

    compile gradleApi()

    compile 'org.apache.xmlgraphics:batik-transcoder:1.9.1'
    compile 'org.apache.xmlgraphics:xmlgraphics-commons:2.2'
    compile 'org.apache.xmlgraphics:batik-codec:1.9.1'
    compile 'org.jclarion:image4j:0.7'

    testCompile 'junit:junit:4.12'
}

uploadArchives {
    repositories {
        mavenDeployer {
            repository(url: "file://${buildDir}/repo")
        }
    }
}

task publish(dependsOn: 'uploadArchives') { }